apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: catalogue
  name: catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogue
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: catalogue
    spec:
      containers:
      - image: freemanpolys/catalogue-dsi
        name: catalogue-dsi
        resources: {}
status: {}
